apiVersion: v1
kind: Service
metadata:
  name: kubeit-service
  namespace: default
spec:
  selector:
    app: kubeit
  ports:
    - protocol: TCP
      port: 7080
      targetPort: 7080
  type: ClusterIP
